# Generated by Django 3.1.4 on 2020-12-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20201207_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='article',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
