# Generated by Django 3.1.4 on 2020-12-07 15:10

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=wagtail.core.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
