# Generated by Django 3.1.4 on 2020-12-07 15:33

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_attr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='attr',
            field=wagtail.core.fields.StreamField([('Row', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(label='name', max_length=64)), ('value', wagtail.core.blocks.CharBlock(label='value', max_length=128))]))], blank=True),
        ),
    ]
